#ifndef OGRECAM_CONFIG_H
#define OGRECAM_CONFIG_H

#define CONFIG_FPS 60
#define CONFIG_DT 0.1
#define CONFIG_SPRING_KS 0.0250
#define CONFIG_SPRING_KD 0.0004
#define CONFIG_GRAVITY  -0.0080

#endif //OGRECAM_CONFIG_H
